export interface ManagedStudent {
  id: string; // e.g. "BF-2026-09-8492"
  studentName: string;
  level: string; // "SD UMUM", "Calistung", "SMP", "SMA UTBK"
  grade: string; // "Kelas 4 SD", "Kelas 2 SD", "Kelas 12 SMA"
  schoolOrigin: string; // "SD Tarakanita Magelang"
  parentName: string;
  parentRelation: 'Ibu' | 'Ayah' | 'Wali';
  whatsapp: string;
  address: string;
  district: string; // "Secang", "Mertoyudan", "Muntilan", "Mungkid", "Borobudur", "Tegalrejo"
  tutorName: string;
  subjects: string[];
  packageSessions: number;
  completedSessions: number;
  status: 'aktif' | 'perlu_perpanjang' | 'cuti';
  joinDate: string;
  lastEvaluationScore?: number;
  notes?: string;
  isFromFirestore?: boolean;
}

export const INITIAL_MANAGED_STUDENTS: ManagedStudent[] = [
  {
    id: 'BF-2026-09-8492',
    studentName: 'Kevin Pratama',
    level: 'SD UMUM',
    grade: 'Kelas 4 SD',
    schoolOrigin: 'SD Tarakanita Magelang',
    parentName: 'Ibu Deasy Kurnia',
    parentRelation: 'Ibu',
    whatsapp: '085173230198',
    address: 'Jl. Raya Secang No. 42 (Dekat Pasar Secang)',
    district: 'Secang',
    tutorName: 'Kak Anindya, S.Pd.',
    subjects: ['Tematik', 'Matematika', 'IPA Terpadu'],
    packageSessions: 8,
    completedSessions: 6,
    status: 'aktif',
    joinDate: '2026-08-10',
    lastEvaluationScore: 92,
    notes: 'Siswa sangat antusias pada konsep perkalian pecahan dan pemecahan soal cerita.',
  },
  {
    id: 'BF-2026-09-8493',
    studentName: 'Michelle Gunawan',
    level: 'SD UMUM',
    grade: 'Kelas 4 SD',
    schoolOrigin: 'SD Kanisius Muntilan',
    parentName: 'Bpk. Hendra Gunawan',
    parentRelation: 'Ayah',
    whatsapp: '081228945671',
    address: 'Jl. Pemuda No. 88, Muntilan (Dekat Klenteng Hok An Kiong)',
    district: 'Muntilan',
    tutorName: 'Kak Dimas Arya, S.Si.',
    subjects: ['Matematika', 'IPA Fisika Dasar'],
    packageSessions: 8,
    completedSessions: 7,
    status: 'perlu_perpanjang',
    joinDate: '2026-08-12',
    lastEvaluationScore: 88,
    notes: 'Sisa 1 sesi lagi. Wali sudah dihubungi untuk perpanjangan paket SPP bulan Oktober.',
  },
  {
    id: 'BF-2026-09-8494',
    studentName: 'Farhan Ramadhan',
    level: 'SMA UTBK',
    grade: 'Kelas 12 SMA',
    schoolOrigin: 'SMAN 1 Muntilan',
    parentName: 'Ibu Laila Ramadhani',
    parentRelation: 'Ibu',
    whatsapp: '081398765432',
    address: 'Kompleks Pemkab Magelang, Kota Mungkid',
    district: 'Mungkid',
    tutorName: 'Kak Sarah Larasati, M.Pd.',
    subjects: ['Penalaran Matematika', 'TPS & Literasi Indonesia'],
    packageSessions: 8,
    completedSessions: 5,
    status: 'aktif',
    joinDate: '2026-08-15',
    lastEvaluationScore: 95,
    notes: 'Persiapan SNBT 2027 fokus pada subtes penalaran kuantitatif.',
  },
  {
    id: 'BF-2026-09-8495',
    studentName: 'Naufal Al-Ghifari',
    level: 'SD UMUM',
    grade: 'Kelas 2 SD',
    schoolOrigin: 'SD Negeri Secang 1',
    parentName: 'Ibu Deasy Kurnia',
    parentRelation: 'Ibu',
    whatsapp: '085173230198',
    address: 'Desa Krincing RT 03/RW 02, Kec. Secang',
    district: 'Secang',
    tutorName: 'Kak Siti Rahma, S.Pd.',
    subjects: ['Calistung Fonik', 'Bahasa Jawa Mulok', 'Matematika Dasar'],
    packageSessions: 8,
    completedSessions: 4,
    status: 'aktif',
    joinDate: '2026-08-20',
    lastEvaluationScore: 89,
    notes: 'Mendapat diskon saudara kandung (kakak Kevin Pratama). Lancar membaca teks 2 suku kata.',
  },
  {
    id: 'BF-2026-09-8496',
    studentName: 'Adelia Putri Wardani',
    level: 'SD UMUM',
    grade: 'Kelas 5 SD',
    schoolOrigin: 'SD Muhammadiyah Mertoyudan',
    parentName: 'Ibu Ratna Dewi',
    parentRelation: 'Ibu',
    whatsapp: '085712345678',
    address: 'Perum Lembah Hijau Blok C-12, Mertoyudan',
    district: 'Mertoyudan',
    tutorName: 'Kak Anindya, S.Pd.',
    subjects: ['Matematika', 'Bahasa Inggris', 'IPAS'],
    packageSessions: 8,
    completedSessions: 2,
    status: 'aktif',
    joinDate: '2026-09-02',
    lastEvaluationScore: 91,
    notes: 'Fokus pemahaman materi pecahan desimal dan tata bahasa present tense.',
  },
  {
    id: 'BF-2026-09-8497',
    studentName: 'Clarissa Aurelia',
    level: 'SMP',
    grade: 'Kelas 8 SMP',
    schoolOrigin: 'SMP Tarakanita Magelang',
    parentName: 'Ibu Martha Nugroho',
    parentRelation: 'Ibu',
    whatsapp: '081987654321',
    address: 'Dusun Janan, Borobudur (Dekat Candi Pawon)',
    district: 'Borobudur',
    tutorName: 'Kak Dimas Arya, S.Si.',
    subjects: ['Matematika Aljabar', 'IPA Fisika & Biologi'],
    packageSessions: 8,
    completedSessions: 8,
    status: 'perlu_perpanjang',
    joinDate: '2026-08-05',
    lastEvaluationScore: 94,
    notes: 'Paket sesi telah habis (8/8 sesi selesai). Perlu konfirmasi perpanjangan sesi UTS.',
  },
  {
    id: 'BF-2026-09-8498',
    studentName: 'Dimas Saputra',
    level: 'SD UMUM',
    grade: 'Kelas 3 SD',
    schoolOrigin: 'SDN Muntilan 2',
    parentName: 'Bpk. Agus Saputra',
    parentRelation: 'Ayah',
    whatsapp: '082133445566',
    address: 'Jl. Veteran No. 15, Muntilan',
    district: 'Muntilan',
    tutorName: 'Kak Siti Rahma, S.Pd.',
    subjects: ['Tematik', 'Matematika Dasar', 'Bahasa Indonesia'],
    packageSessions: 8,
    completedSessions: 3,
    status: 'aktif',
    joinDate: '2026-08-28',
    lastEvaluationScore: 86,
    notes: 'Perkembangan hafalan perkalian 1-5 meningkat pesat dengan metode flash card.',
  },
  {
    id: 'BF-2026-09-8499',
    studentName: 'Rizky Pratama',
    level: 'SMA UTBK',
    grade: 'Kelas 11 SMA',
    schoolOrigin: 'SMA Taruna Nusantara Magelang',
    parentName: 'Bpk. Heru Pratama',
    parentRelation: 'Ayah',
    whatsapp: '081322334455',
    address: 'Jl. Raya Magelang-Purworejo Km. 6, Mertoyudan',
    district: 'Mertoyudan',
    tutorName: 'Kak Sarah Larasati, M.Pd.',
    subjects: ['Kimia Stoikiometri', 'Bahasa Inggris TOEFL Prep'],
    packageSessions: 8,
    completedSessions: 6,
    status: 'aktif',
    joinDate: '2026-08-14',
    lastEvaluationScore: 93,
    notes: 'Konsisten latihan soal kimia analisis kuantitatif dan listening comprehension.',
  },
  {
    id: 'BF-2026-09-8500',
    studentName: 'Zahra Amelia',
    level: 'Calistung',
    grade: 'TK B / Transisi SD',
    schoolOrigin: 'TK Pertiwi Secang',
    parentName: 'Ibu Fatimah Az-Zahra',
    parentRelation: 'Ibu',
    whatsapp: '085290112233',
    address: 'Dusun Krajan RT 01/RW 01, Secang',
    district: 'Secang',
    tutorName: 'Kak Siti Rahma, S.Pd.',
    subjects: ['Fonik Membaca', 'Menulis Halus', 'Hitung Angka 1-50'],
    packageSessions: 8,
    completedSessions: 1,
    status: 'aktif',
    joinDate: '2026-09-18',
    lastEvaluationScore: 90,
    notes: 'Sangat ceria, mulai lancar menyambung bunyi huruf konsonan-vokal (ba, ca, da).',
  },
];

export const MAGELANG_DISTRICTS = [
  'Semua Wilayah Magelang',
  'Secang',
  'Mertoyudan',
  'Muntilan',
  'Mungkid',
  'Borobudur',
  'Tegalrejo',
  'Salaman',
  'Grabag',
  'Tempuran',
  'Sawangan',
];

export const AVAILABLE_TUTORS = [
  'Kak Anindya, S.Pd. (SD UMUM & Matematika)',
  'Kak Dimas Arya, S.Si. (Sains & Fisika SMP/SMA)',
  'Kak Sarah Larasati, M.Pd. (Literasi & UTBK SMA)',
  'Kak Siti Rahma, S.Pd. (Calistung & SD Kelas Rendah)',
];
